"""add_suggestion_count

Revision ID: 1a1bdf5f4393
Revises: 802f675ec86a
Create Date: 2026-02-21 11:15:30.416166+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a1bdf5f4393'
down_revision: Union[str, None] = '802f675ec86a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('suggestion_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'suggestion_count')
    # ### end Alembic commands ###
