"""add title and description

Revision ID: 802f675ec86a
Revises: 1e245e8dc322
Create Date: 2026-02-21 08:14:44.943253+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '802f675ec86a'
down_revision: Union[str, None] = '1e245e8dc322'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('title', sa.String(length=255), nullable=True))
    op.add_column('videos', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'description')
    op.drop_column('videos', 'title')
    # ### end Alembic commands ###
